apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmfinder-ui-deployment
spec:
  selector:
    matchLabels:
      app: pharmfinder
  replicas: 1
  template:
    metadata:
      labels:
        app: pharmfinder
    spec:
      containers:
      - name: pharmfinder-ui-container
        image: saadrahmanwarsi/pharmfinder-ui:1.0.0
        ports:
        - containerPort: 8080